Asad/chore/site theme
hicsail/cycm-ionic pull request #12
Opened 2023-12-11 16:13 UTC by am5815

Added some theme updates and mobile responsiveness.

2023-12-11 16:52 UTC, wenhwang97 reviewed
Very colorful. Just some advices on sizing and spacing.

2023-12-11 16:52 UTC, wenhwang97 commented on src/pages/Index.tsx
> +          </div>
I think maybe this section should be wider. The size right now is the same as those cards below.

2023-12-11 16:52 UTC, wenhwang97 commented on src/components/IonicCard.tsx
>        >
Now they have the same height. Maybe add some space between the paragraph and the "Visit" button as well.

2023-12-13 15:33 UTC, am5815 commented on src/pages/Index.tsx
> +          </div>
The text is not too much in length and if its wider, its just one line which seems bland. I think maybe we can play with sizing and colors but for now, I think keeping the width small to it appears on multiple lines looks better.

2023-12-13 15:33 UTC, am5815 commented on src/components/IonicCard.tsx
>        >
addressed in new commit

2023-12-13 16:01 UTC, wenhwang97 requested changes
I think the hardcoded height messed up a lot of components in the card. I just found a way to fix it, which should solve the issue on home page and resource page.

2023-12-13 16:47 UTC, wenhwang97 approved these changes

2023-12-13 16:48 UTC, merged